name: AHDWEBTEST
favicon: null
layout_spectrum: 0.9473972290288657
typography_spectrum: 0.5390445601660758
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.007289366563782096
  lightness: 0.37862510420382023
  saturation: 0.45448701339773834
  rhythmicContrast: 0.43324138363823295
purpose: []
